Make xrange py3 compatible
In py3,
Xrange is renamed to range,
so it needs to be modified to make it compatible.
the code:
print (xrange(5))
Traceback (most recent call last):
  File "code", line 4, in <module>
    print (xrange(5))
NameError: name 'xrange' is not defined
This patch will fix the issue.

Change-Id: I3a368aee645864faacd203436b326a7df1c79738
Closes-Bug: #1596127